import React from "react";
import CloudAnimation from "./CloudAnimation";

const Header = () => {
  // Configuration for an extremely dense, 75-cloud scape.
  // NOTE: This is very demanding on the browser's rendering engine and is
  // best suited for powerful desktop machines.
  // Strategy: 3 layers of 25 clouds each, with systematic property
  // variation to fill the space without looking overtly repetitive.
  const cloudLayers = [
    // --- Foreground Layer (25 clouds): Fastest, most opaque ---
    {
      id: "fg-1",
      speed: 4.0,
      size: "large",
      opacity: 0.9,
      delay: 0.2,
      top: "90px",
    },
    {
      id: "fg-2",
      speed: 4.2,
      size: "medium",
      opacity: 0.85,
      delay: 0.4,
      top: "110px",
    },
    {
      id: "fg-3",
      speed: 3.8,
      size: "small",
      opacity: 0.9,
      delay: 0.6,
      top: "55px",
    },
    {
      id: "fg-4",
      speed: 5.0,
      size: "medium",
      opacity: 0.8,
      delay: 0.8,
      top: "70px",
    },
    {
      id: "fg-5",
      speed: 4.5,
      size: "large",
      opacity: 0.85,
      delay: 1.0,
      top: "40px",
    },
    {
      id: "fg-6",
      speed: 4.8,
      size: "small",
      opacity: 0.8,
      delay: 1.2,
      top: "125px",
    },
    {
      id: "fg-7",
      speed: 3.5,
      size: "medium",
      opacity: 0.9,
      delay: 1.4,
      top: "10px",
    },
    {
      id: "fg-8",
      speed: 4.6,
      size: "large",
      opacity: 0.8,
      delay: 1.6,
      top: "105px",
    },
    {
      id: "fg-9",
      speed: 4.1,
      size: "small",
      opacity: 0.85,
      delay: 1.8,
      top: "85px",
    },
    {
      id: "fg-10",
      speed: 4.9,
      size: "medium",
      opacity: 0.8,
      delay: 2.0,
      top: "20px",
    },
    {
      id: "fg-11",
      speed: 3.9,
      size: "large",
      opacity: 0.9,
      delay: 2.2,
      top: "65px",
    },
    {
      id: "fg-12",
      speed: 4.3,
      size: "small",
      opacity: 0.85,
      delay: 2.4,
      top: "115px",
    },
    {
      id: "fg-13",
      speed: 4.7,
      size: "medium",
      opacity: 0.8,
      delay: 2.6,
      top: "30px",
    },
    {
      id: "fg-14",
      speed: 3.7,
      size: "large",
      opacity: 0.9,
      delay: 2.8,
      top: "95px",
    },
    {
      id: "fg-15",
      speed: 5.1,
      size: "small",
      opacity: 0.8,
      delay: 3.0,
      top: "5px",
    },
    {
      id: "fg-16",
      speed: 4.4,
      size: "medium",
      opacity: 0.85,
      delay: 3.2,
      top: "120px",
    },
    {
      id: "fg-17",
      speed: 3.6,
      size: "large",
      opacity: 0.9,
      delay: 3.4,
      top: "50px",
    },
    {
      id: "fg-18",
      speed: 5.2,
      size: "small",
      opacity: 0.8,
      delay: 3.6,
      top: "80px",
    },
    {
      id: "fg-19",
      speed: 4.0,
      size: "medium",
      opacity: 0.85,
      delay: 3.8,
      top: "15px",
    },
    {
      id: "fg-20",
      speed: 4.8,
      size: "large",
      opacity: 0.8,
      delay: 4.0,
      top: "100px",
    },
    {
      id: "fg-21",
      speed: 3.8,
      size: "small",
      opacity: 0.9,
      delay: 4.2,
      top: "60px",
    },
    {
      id: "fg-22",
      speed: 4.6,
      size: "medium",
      opacity: 0.85,
      delay: 4.4,
      top: "130px",
    },
    {
      id: "fg-23",
      speed: 4.2,
      size: "large",
      opacity: 0.8,
      delay: 4.6,
      top: "35px",
    },
    {
      id: "fg-24",
      speed: 5.0,
      size: "small",
      opacity: 0.85,
      delay: 4.8,
      top: "90px",
    },
    {
      id: "fg-25",
      speed: 3.9,
      size: "medium",
      opacity: 0.9,
      delay: 5.0,
      top: "0px",
    },

    // --- Middle Layer (25 clouds): Medium speed and opacity ---
    {
      id: "mid-1",
      speed: 8.0,
      size: "medium",
      opacity: 0.7,
      delay: 0.1,
      top: "25px",
    },
    {
      id: "mid-2",
      speed: 7.0,
      size: "large",
      opacity: 0.65,
      delay: 0.3,
      top: "5px",
    },
    {
      id: "mid-3",
      speed: 9.0,
      size: "small",
      opacity: 0.7,
      delay: 0.5,
      top: "80px",
    },
    {
      id: "mid-4",
      speed: 8.5,
      size: "medium",
      opacity: 0.6,
      delay: 0.7,
      top: "110px",
    },
    {
      id: "mid-5",
      speed: 7.5,
      size: "large",
      opacity: 0.65,
      delay: 0.9,
      top: "50px",
    },
    {
      id: "mid-6",
      speed: 9.5,
      size: "small",
      opacity: 0.6,
      delay: 1.1,
      top: "15px",
    },
    {
      id: "mid-7",
      speed: 8.2,
      size: "medium",
      opacity: 0.7,
      delay: 1.3,
      top: "95px",
    },
    {
      id: "mid-8",
      speed: 7.8,
      size: "large",
      opacity: 0.6,
      delay: 1.5,
      top: "35px",
    },
    {
      id: "mid-9",
      speed: 8.8,
      size: "small",
      opacity: 0.65,
      delay: 1.7,
      top: "120px",
    },
    {
      id: "mid-10",
      speed: 7.2,
      size: "medium",
      opacity: 0.7,
      delay: 1.9,
      top: "60px",
    },
    {
      id: "mid-11",
      speed: 9.2,
      size: "large",
      opacity: 0.6,
      delay: 2.1,
      top: "100px",
    },
    {
      id: "mid-12",
      speed: 8.3,
      size: "small",
      opacity: 0.65,
      delay: 2.3,
      top: "45px",
    },
    {
      id: "mid-13",
      speed: 7.7,
      size: "medium",
      opacity: 0.7,
      delay: 2.5,
      top: "0px",
    },
    {
      id: "mid-14",
      speed: 8.6,
      size: "large",
      opacity: 0.6,
      delay: 2.7,
      top: "75px",
    },
    {
      id: "mid-15",
      speed: 9.8,
      size: "small",
      opacity: 0.65,
      delay: 2.9,
      top: "125px",
    },
    {
      id: "mid-16",
      speed: 7.4,
      size: "medium",
      opacity: 0.7,
      delay: 3.1,
      top: "20px",
    },
    {
      id: "mid-17",
      speed: 8.1,
      size: "large",
      opacity: 0.6,
      delay: 3.3,
      top: "88px",
    },
    {
      id: "mid-18",
      speed: 9.3,
      size: "small",
      opacity: 0.65,
      delay: 3.5,
      top: "58px",
    },
    {
      id: "mid-19",
      speed: 7.6,
      size: "medium",
      opacity: 0.7,
      delay: 3.7,
      top: "108px",
    },
    {
      id: "mid-20",
      speed: 8.9,
      size: "large",
      opacity: 0.6,
      delay: 3.9,
      top: "18px",
    },
    {
      id: "mid-21",
      speed: 7.1,
      size: "small",
      opacity: 0.65,
      delay: 4.1,
      top: "68px",
    },
    {
      id: "mid-22",
      speed: 9.6,
      size: "medium",
      opacity: 0.6,
      delay: 4.3,
      top: "98px",
    },
    {
      id: "mid-23",
      speed: 8.4,
      size: "large",
      opacity: 0.65,
      delay: 4.5,
      top: "28px",
    },
    {
      id: "mid-24",
      speed: 7.9,
      size: "small",
      opacity: 0.7,
      delay: 4.7,
      top: "118px",
    },
    {
      id: "mid-25",
      speed: 9.1,
      size: "medium",
      opacity: 0.6,
      delay: 4.9,
      top: "38px",
    },

    // --- Background Layer (25 clouds): Slowest, most transparent ---
    {
      id: "bg-1",
      speed: 15,
      size: "large",
      opacity: 0.4,
      delay: 0.15,
      top: "0px",
    },
    {
      id: "bg-2",
      speed: 12,
      size: "medium",
      opacity: 0.5,
      delay: 0.35,
      top: "65px",
    },
    {
      id: "bg-3",
      speed: 18,
      size: "small",
      opacity: 0.45,
      delay: 0.55,
      top: "90px",
    },
    {
      id: "bg-4",
      speed: 14,
      size: "large",
      opacity: 0.35,
      delay: 0.75,
      top: "120px",
    },
    {
      id: "bg-5",
      speed: 16,
      size: "medium",
      opacity: 0.4,
      delay: 0.95,
      top: "30px",
    },
    {
      id: "bg-6",
      speed: 13,
      size: "small",
      opacity: 0.5,
      delay: 1.15,
      top: "75px",
    },
    {
      id: "bg-7",
      speed: 17,
      size: "large",
      opacity: 0.3,
      delay: 1.35,
      top: "100px",
    },
    {
      id: "bg-8",
      speed: 12.5,
      size: "medium",
      opacity: 0.45,
      delay: 1.55,
      top: "20px",
    },
    {
      id: "bg-9",
      speed: 19,
      size: "small",
      opacity: 0.4,
      delay: 1.75,
      top: "50px",
    },
    {
      id: "bg-10",
      speed: 14.5,
      size: "large",
      opacity: 0.35,
      delay: 1.95,
      top: "80px",
    },
    {
      id: "bg-11",
      speed: 15.5,
      size: "medium",
      opacity: 0.4,
      delay: 2.15,
      top: "10px",
    },
    {
      id: "bg-12",
      speed: 13.5,
      size: "small",
      opacity: 0.5,
      delay: 2.35,
      top: "115px",
    },
    {
      id: "bg-13",
      speed: 20,
      size: "large",
      opacity: 0.3,
      delay: 2.55,
      top: "40px",
    },
    {
      id: "bg-14",
      speed: 12.8,
      size: "medium",
      opacity: 0.45,
      delay: 2.75,
      top: "95px",
    },
    {
      id: "bg-15",
      speed: 16.5,
      size: "small",
      opacity: 0.4,
      delay: 2.95,
      top: "5px",
    },
    {
      id: "bg-16",
      speed: 14.2,
      size: "large",
      opacity: 0.35,
      delay: 3.15,
      top: "125px",
    },
    {
      id: "bg-17",
      speed: 17.5,
      size: "medium",
      opacity: 0.4,
      delay: 3.35,
      top: "55px",
    },
    {
      id: "bg-18",
      speed: 13.2,
      size: "small",
      opacity: 0.5,
      delay: 3.55,
      top: "85px",
    },
    {
      id: "bg-19",
      speed: 18.5,
      size: "large",
      opacity: 0.3,
      delay: 3.75,
      top: "25px",
    },
    {
      id: "bg-20",
      speed: 15.2,
      size: "medium",
      opacity: 0.45,
      delay: 3.95,
      top: "105px",
    },
    {
      id: "bg-21",
      speed: 19.5,
      size: "small",
      opacity: 0.4,
      delay: 4.15,
      top: "65px",
    },
    {
      id: "bg-22",
      speed: 12.2,
      size: "large",
      opacity: 0.5,
      delay: 4.35,
      top: "15px",
    },
    {
      id: "bg-23",
      speed: 16.8,
      size: "medium",
      opacity: 0.35,
      delay: 4.55,
      top: "112px",
    },
    {
      id: "bg-24",
      speed: 14.8,
      size: "small",
      opacity: 0.4,
      delay: 4.75,
      top: "48px",
    },
    {
      id: "bg-25",
      speed: 17.2,
      size: "large",
      opacity: 0.3,
      delay: 4.95,
      top: "92px",
    },
  ];

  return (
    <header
      className="relative w-full overflow-hidden"
      style={{
        height: "200px",
      }}
    >
      {/* Cloud animation layers */}
      {cloudLayers.map((cloud) => (
        <div
          key={cloud.id}
          className="absolute w-full"
          style={{
            top: cloud.top,
            height: "50px",
            left: 0,
            right: 0,
          }}
        >
          <CloudAnimation
            speed={cloud.speed}
            size={cloud.size}
            opacity={cloud.opacity}
            delay={cloud.delay}
          />
        </div>
      ))}

      {/* Optional header content overlay */}
      <div className="relative z-10 h-full flex items-center justify-center">
        {/* This space can be used for navigation or branding if needed */}
      </div>
    </header>
  );
};

export default Header;
